overblog_graphql:
  security: '%kernel.debug%'
  definitions:
    schema:
      query: Query
      mutation: Mutation
    mappings:
      types:
        - type: yaml
          dir: "%kernel.project_dir%/config/graphql/types"
          suffix: ~
