overblog_graphql:
  definitions:
    schema:
      query: Query
      types: ["DateTime"]
    mappings:
      types:
        - type: yaml
          dir: "%kernel.project_dir%/config/graphql/types"
          suffix: ~
