Mutation:
  type: object
  config:
    fields:
      UpdatePost:
        type: Post!
        args:
          input:
            type: UpdatePostInput!
        resolve: "@=mutation('update_post', [args['input']['id'], args['input']['topic'], args['input']['content']])"
      RegisterUser:
        type: User!
        args:
          input:
            type: RegisterUserInput
        resolve: "@=mutation('register_user', [args['input']['email'], args['input']['password']])"
      LoginUser:
        type: Token!
        args:
          input:
            type: RegisterUserInput
        resolve: "@=mutation('login_user', [args['input']['email'], args['input']['password']])"

UpdatePostInput:
  type: input-object
  config:
    fields:
      id:
        type: Int!
      topic:
        type: String!
      content:
        type: String!
        
RegisterUserInput:
  type: input-object
  config:
    fields:
      email:
        type: String!
      password:
        type: String!
