Post:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\PostResolver", [info, value, args])'
    fields:
      id:
        type: Int!
      topic:
        type: String!
      content:
        type: String!
      createdAt:
        type: String!
        args:
          format:
            type: String
        resolve: '@=resolver("App\\GraphQL\\Resolver\\DateTimeResolver", [value.createdAt(), args["format"]])'
      numberOfLikes:
        type: Int!
      tags:
        type: tagConnection
        argsBuilder: Relay::ForwardConnection
