Post:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\PostResolver", [info, value, args])'
    fields:
      id:
        type: Int!
      topic:
        type: String!
      content:
        type: String!
      createdAt:
        type: DateTime!
      numberOfLikes:
        type: Int!
      tags:
        type: tagConnection
        argsBuilder: Relay::ForwardConnection
