Query:
  type: object
  config:
    fields:
      author:
        type: Author
        args:
          id:
            type: Int
        resolve: '@=resolver("App\\GraphQL\\Resolver\\AuthorResolver::find", [args["id"]])'
      authors:
        type: "[Author]"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\AuthorResolver::all")'
